# Violent word analysis

In this notebook, we will apply a word counter using various lists of violent terms to analyze the plot data in the clean dataset.

### Imports

In [1]:
import sys
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Add the project root directory (not src) to sys.path
sys.path.append(os.path.abspath("../data/"))

# Now import the DataLoader class
from data_loading import DataLoader

raw = '../../data/RAW/'
clean = '../../data/CLEAN'

In [3]:
# Add the directory containing the script to sys.path
sys.path.append(os.path.abspath("../model"))

# Now you can import the script like a module
from Word_counter import WordCounter

## Load the data

In [4]:
#load raw data
data_loader = DataLoader(raw,clean)
MovieData = data_loader.clean_movie_data()

In [5]:
MovieData

,Movie name,Release date,Box office revenue,Languages,Countries,Genres,Plot
Wikipedia movie ID,,,,,,,
975900,Ghosts of Mars,2001-08-24,14010832.0,English Language,United States of America,"Thriller, Science Fiction, Horror, Adventure, ...","set in the second half of the 22nd century, th..."
6631279,Little city,1997-04-04,NaN,English Language,United States of America,"Romantic comedy, Ensemble Film, Comedy-drama, ...","adam, a san francisco-based artist who works a..."
77856,Mary Poppins,1964-08-27,102272727.0,English Language,United States of America,"Children's/Family, Musical, Fantasy, Comedy, D...",the film opens with mary poppins perched in a...
21926710,White on Rice,2009-05-31,NaN,NaN,United States of America,"Romantic comedy, Romance Film, Comedy, Indie",jimmy ([[hiroshi watanabe loves dinosaurs and...
156558,Baby Boy,2001-06-27,29381649.0,English Language,United States of America,"Crime Fiction, Drama, Coming of age",a young 20-year-old named jody lives with his...
...,...,...,...,...,...,...,...
25011340,Dot.Kill,2005-03-08,NaN,NaN,United States of America,"Thriller, Crime Thriller, Action, Psychologica...","charlie daines , is a morphine-addicted detect..."
7761830,Spaced Invaders,1990-04-27,15369573.0,English Language,United States of America,"Alien Film, Science Fiction, Family Film, Come...","the space armada from mars, known as the imper..."
1918494,State and Main,2000-08-26,6944471.0,"Italian Language, English Language","France, United States of America","Parody, Americana, Comedy",havoc is wrought on the inhabitants of a small...
664006,Guilty as Sin,1993-06-04,22886222.0,NaN,United States of America,"Thriller, Erotic thriller, Psychological thril...",jennifer haines is an up-and-coming chicago a...
35228177,Mermaids: The Body Found,2011-03-19,NaN,English Language,United States of America,Drama,two former national oceanic atmospheric admini...

## Initialize the word counter

In [6]:
Word_Counter = WordCounter(data_loader,MovieData)

## Perform word count and save the data

In [7]:
Count = Word_Counter.violent_word_count("All")

word count for the list : Physical_violence
word count for the list : Psychological_violence
total count
calculate density
done !

In [8]:
Count

,word_count_Physical_violence,word_count_Psychological_violence,total_count,density word_count_Physical_violence,density word_count_Psychological_violence
Wikipedia movie ID,,,,,
3217,3,3,479,0.006263,0.006263
3333,1,5,858,0.001166,0.005828
3746,3,3,669,0.004484,0.004484
3837,7,3,631,0.011094,0.004754
3947,7,7,930,0.007527,0.007527
...,...,...,...,...,...
36956792,6,2,780,0.007692,0.002564
37067980,0,0,50,0.000000,0.000000
37210334,1,1,259,0.003861,0.003861
37257312,0,0,131,0.000000,0.000000
37373877,0,2,168,0.000000,0.011905

In [9]:
# save the result
Count.to_csv(clean + "/word_count.csv")